export const exercises = [
    {
        id: "context",
        title: "Practice React Context by building a TextField component using composition",
        date: "May 19",
        readTime: "1 min",
        url: "https://reactpractice.dev/exercise/practice-react-context-by-building-a-textfield-component-using-composition/",
        description:
            "The exercise 'Practice React Context by building a TextField component using composition' on ReactPractice.dev challenges you to create a reusable TextField component in React. " +
            "Using the Context API and composition, the component should allow adding a Label and an Input that are linked via a unique ID generated by React's useId hook, ensuring proper accessibility with the HTML 'for' attribute. " +
            "This exercise is inspired by the React-Aria TextField and Shadcn FormItem components, and it helps practice building flexible, composable, and accessible form components in React while managing state and context effectively.",
    },
    {
        id: "linkedin",
        title: 'Build the Linkedin "Add experience" form',
        date: "Apr 10",
        readTime: "3 min",
    },
    {
        id: "github-search",
        title: "Build a Github repositories search page with sorting and pagination",
        date: "Mar 12",
        readTime: "1 min",
        url: "https://reactpractice.dev/exercise/build-a-github-repositories-search-page-with-sorting-and-pagination/",
        description:
            "The exercise 'Build a GitHub Repositories Search Page with Sorting and Pagination' on ReactPractice.dev challenges you to build a React application that allows users to search for GitHub repositories. " +
            "Users should be able to sort the results by best match, number of stars, or most recently updated, as well as choose how many items are displayed per page. " +
            "The results must be paginated, and React Query is recommended for fetching and caching data. " +
            "This functionality simulates GitHub's repository search page, and during development, a mock JSON or API key can be used to avoid API rate limits. " +
            "The exercise helps practice integrating APIs, implementing dynamic search, sorting, pagination, and handling asynchronous data efficiently in React.",
    },
    {
        id: "usefetch",
        title: "Build a custom useFetch hook",
        date: "Feb 20",
        readTime: "2 min",
    },
    {
        id: "budget",
        title: "Build a budget app dashboard",
        date: "Feb 03",
        readTime: "1 min",
    },
    {
        id: "newsletter",
        title: "Use React 19 form features to refactor a Newsletter Subscribe form",
        date: "Dec 18",
        readTime: "1 min",
    },
    {
        id: "restaurant",
        title: "Build a restaurant reservation widget",
        date: "Dec 05",
        readTime: "1 min",
    },
    {
        id: "pomodoro",
        title: "Build a Pomodoro app",
        date: "Nov 20",
        readTime: "1 min",
    },
    {
        id: "holidays",
        title: "Build a Public holidays app",
        date: "Nov 04",
        readTime: "1 min",
    },
    {
        id: "auth",
        title: "Build a simple auth app with Supabase",
        date: "Jul 22",
        readTime: "1 min",
    },
    {
        id: "issues",
        title: "Build the Github Issue Filter component",
        date: "Jul 16",
        readTime: "1 min",
    },
    {
        id: "pokemon",
        title: "Build an infinite scrolling list of Pokémon",
        date: "Jul 01",
        readTime: "1 min",
    },
    {
        id: "typewriter",
        title: "Build a Typewriter effect component",
        date: "Jun 24",
        readTime: "1 min",
    },
    {
        id: "hackernews",
        title: "Show top 10 articles from Hacker News",
        date: "Jun 17",
        readTime: "1 min",
    },
    {
        id: "todo",
        title: "Build a drag and drop to-do list",
        date: "Jun 09",
        readTime: "1 min",
    },
    {
        id: "notes",
        title: "Build a notes app with React Query and json server - starting from failing unit tests!",
        date: "May 30",
        readTime: "2 min",
    },
    {
        id: "memory",
        title: "Build a memory game",
        date: "Apr 30",
        readTime: "1 min",
    },
    {
        id: "accordion",
        title: "Build an Accordion component",
        date: "Apr 23",
        readTime: "2 min",
    },
    {
        id: "localstorage",
        title: "Add persistence to local storage for an existing app",
        date: "Apr 19",
        readTime: "1 min",
    },
    {
        id: "pokemon-load",
        title: 'Build a paginated Pokemons list with a "Load more" button - starting from failing unit tests!',
        date: "Jun 23",
        readTime: "2 min",
    },
];
