name: Frontend CI

on:
    push:
        branches: [master, dev]
    pull_request:
        branches: [master, dev]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ steps.setup-node.outputs.node-version }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - run: npm ci
            - run: npm run build
            - run: npm run test
